### ISSUE TITLE
bridge: '1.0.0-alpha4' not compatible with di '3.3.4'

### ISSUE THREAD

**Issue by SatWiz** [dart-bridge/bridge#5]
Hi Emil,
while trying to play bridge with material design lite (mdl: '1.0.0') I got stucked with compatible issues loading di 3.3.4. Do you have any plans to make Bridge di compatible?

**Comment by emilniklas** [comment]
Does it say what dependency is conflicting?

**Comment by SatWiz** [comment]
```
name: app
version: 0.1.0
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  di: ^3.3.4
  bridge: '1.0.0-alpha4'
  mdl: '^1.0.0'

transformers:
  - di
```

-> % pub get
Resolving dependencies... (6.5s)
Package analyzer has no versions that match >=0.22.0 <0.25.0 derived from:
- di 3.3.4 depends on version >=0.22.0 <0.25.0

If I accept any version for Bridge than it will install bridge version 0.2 with di: 3.3.4
